# Generated by Django 5.2.7 on 2025-11-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orders_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orders',
            new_name='order',
        ),
    ]
