# Generated by Django 5.2.7 on 2025-11-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_orders_status_orders_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('sent', 'Отправлен')], default='new', max_length=10),
        ),
    ]
